--CHECK TABLE IN assignment - 2.sql FILE
--https://github.com/AyushGinoya/SQL/blob/main/assignment%20-%202.sql


SELECT * FROM EMPLOYEE
SELECT * FROM DEPARTMENTS
SELECT * FROM PROJECTS


--1. List all employees along with their department names. 
SELECT FIRSTNAME,LASTNAME,D.DEPARTMENTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID


--2. Find the department name and the manager's name. 
SELECT (FIRSTNAME+' '+LASTNAME) AS MANAGER,D.DEPARTMENTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.EMPLOYEEID = D.MANAGERID


--3. List all projects with their department names. 
SELECT P.PROJECTNAME,D.DEPARTMENTNAME FROM PROJECTS P
INNER JOIN DEPARTMENTS D
ON P.DEPARTMENTID=D.DEPARTMENTID


--4. List all employees along with their department locations. 
SELECT (FIRSTNAME+' '+LASTNAME) AS NAME, D.LOCATION FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;


--5. Find all employees with their respective project names (if they are part of any). 
SELECT (FIRSTNAME+' '+LASTNAME) AS NAME, P.PROJECTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN PROJECTS P
ON P.DEPARTMENTID = D.DEPARTMENTID;


--6. Find all projects and their start dates along with department names. 
SELECT P.PROJECTNAME,P.STARTDATE,D.DEPARTMENTNAME FROM PROJECTS P
INNER JOIN DEPARTMENTS D
ON P.DEPARTMENTID = D.DEPARTMENTID;


--7. List employees who have no department. 
SELECT (FIRSTNAME+' '+LASTNAME) AS NAME FROM EMPLOYEE E
WHERE E.DEPARTMENTID IS NULL;


--8. Find employees along with their department name and project name. 
SELECT (FIRSTNAME+' '+LASTNAME) AS NAME, D.DEPARTMENTNAME, P.PROJECTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN PROJECTS P
ON P.DEPARTMENTID = D.DEPARTMENTID;


--9. Find departments without any projects. 
SELECT D.DEPARTMENTNAME FROM DEPARTMENTS D
WHERE D.DEPARTMENTID NOT IN(SELECT P.DEPARTMENTID FROM PROJECTS P)


--10. List projects along with the department manager's name. 
SELECT P.PROJECTNAME,E.FIRSTNAME,D.DEPARTMENTNAME FROM PROJECTS P
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = P.DEPARTMENTID
INNER JOIN EMPLOYEE E
ON E.EMPLOYEEID = D.MANAGERID


--11. Find the total salary by department. 
SELECT D.DEPARTMENTNAME, SUM(E.SALARY) AS TOTAL_SALARY FROM EMPLOYEE E
JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;


--12. List all employees who work in the same department as the department's manager.
SELECT E.FIRSTNAME,D.DEPARTMENTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.EMPLOYEEID = D.MANAGERID
WHERE E.DEPARTMENTID = D.DEPARTMENTID AND E.EMPLOYEEID != D.MANAGERID


--13. Find employees whose salary is above the average salary of their department. 
SELECT E.FIRSTNAME,E.LASTNAME, D.DEPARTMENTNAME,E.SALARY FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE E.SALARY>( SELECT AVG(E1.SALARY)
    FROM EMPLOYEE E1
    WHERE E1.DEPARTMENTID = E.DEPARTMENTID
    GROUP BY E1.DEPARTMENTID
	)
	

--14. List all departments with more than 5 employees. 
SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS CT FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING  COUNT(E.EMPLOYEEID)>5


--15. Find employees who were hired before their department's manager was hired. 
SELECT E.FIRSTNAME, E.LASTNAME, E.HIREDATE, D.DEPARTMENTNAME, M.FIRSTNAME AS MANAGER_FIRSTNAME, M.HIREDATE AS MANAGER_HIREDATE
FROM EMPLOYEE E
JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
JOIN EMPLOYEE M ON D.MANAGERID = M.EMPLOYEEID
WHERE E.HIREDATE < M.HIREDATE;


--16. Find the highest-paid employee in each department. 
SELECT D.DEPARTMENTNAME, E.FIRSTNAME FROM EMPLOYEE E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE E.SALARY = (SELECT MAX(E1.SALARY)
    FROM EMPLOYEE E1
    WHERE E1.DEPARTMENTID = E.DEPARTMENTID)


--17. List all projects that have not yet started. 
SELECT * FROM PROJECTS P
WHERE P.STARTDATE>GETDATE();


--18. Find departments with projects that have been completed. 
SELECT * FROM PROJECTS P
WHERE P.ENDDATE<GETDATE();


--19. Find employees who have worked in departments with more than 3 projects. 
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME
FROM EMPLOYEE E
JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTID IN (
    SELECT P.DEPARTMENTID
    FROM PROJECTS P
    GROUP BY P.DEPARTMENTID
    HAVING COUNT(P.PROJECTID) > 3
);


--20. Find all projects managed by employees older than 40 years. 
SELECT P.PROJECTNAME, P.STARTDATE, P.ENDDATE, D.DEPARTMENTNAME
FROM PROJECTS P
JOIN DEPARTMENTS D ON P.DEPARTMENTID = D.DEPARTMENTID
JOIN EMPLOYEE E ON D.MANAGERID = E.EMPLOYEEID
WHERE DATEDIFF(YEAR, E.DOB, GETDATE()) > 40;


--21. Find the average salary of each department. 
SELECT D.DEPARTMENTNAME, AVG(E.SALARY) AS AVG_SALARY
FROM DEPARTMENTS D
JOIN EMPLOYEE E ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;


--22. List the number of projects handled by each department. 
SELECT D.DEPARTMENTNAME, COUNT(P.PROJECTID) AS PROJECT_COUNT FROM DEPARTMENTS D
LEFT JOIN PROJECTS P 
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;


--23. Find employees who are not managers but are in the same department as their managers. 
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME
FROM EMPLOYEE E
JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE E.EMPLOYEEID != D.MANAGERID
AND E.DEPARTMENTID = D.DEPARTMENTID;


--24. List departments that have employees with a salary greater than 100,000. 
SELECT DISTINCT D.DEPARTMENTNAME FROM DEPARTMENTS D
JOIN EMPLOYEE E 
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE E.SALARY > 100000;

--25. Find the department with the most projects. 
SELECT TOP 1 D.DEPARTMENTNAME,COUNT(P.PROJECTID)
FROM DEPARTMENTS D
JOIN PROJECTS P ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
ORDER BY COUNT(P.PROJECTID) DESC


--26. Find all projects that have both started and ended within the same year. 
SELECT P.PROJECTNAME, P.STARTDATE, P.ENDDATE
FROM PROJECTS P
WHERE YEAR(P.STARTDATE) = YEAR(P.ENDDATE);


--27. List employees along with their project details if they are part of a project that started  after 2023. 
SELECT E.FIRSTNAME, E.LASTNAME, P.PROJECTNAME, P.STARTDATE, P.ENDDATE
FROM EMPLOYEE E
JOIN PROJECTS P ON E.DEPARTMENTID = P.DEPARTMENTID
WHERE P.STARTDATE > '2023-01-01';


--28. Find departments with the highest total employee salaries. 
SELECT TOP 1 D.DEPARTMENTNAME, SUM(E.SALARY) AS TOTAL_SALARY
FROM DEPARTMENTS D
JOIN EMPLOYEE E ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
ORDER BY TOTAL_SALARY DESC;


--29. List employees working in departments where the manager's salary is less than the average department salary. 
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, M.SALARY AS MANAGER_SALARY, AVG(E1.SALARY) AS AVG_SALARY
FROM EMPLOYEE E
JOIN DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
JOIN EMPLOYEE M ON D.MANAGERID = M.EMPLOYEEID
JOIN EMPLOYEE E1 ON E.DEPARTMENTID = E1.DEPARTMENTID
GROUP BY E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, M.SALARY
HAVING M.SALARY < AVG(E1.SALARY);


--30. List projects that are not associated with any department.
SELECT P.PROJECTNAME, P.STARTDATE, P.ENDDATE
FROM PROJECTS P
LEFT JOIN DEPARTMENTS D ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL;
