--31. FIND THE EMPLOYEE WHO HAS WORKED THE LONGEST IN THEIR CURRENT DEPARTMENT.

SELECT				TOP 1 *
FROM				EMPLOYEE
ORDER BY			HIREDATE ASC


--32. FIND THE AVERAGE SALARY OF EMPLOYEES IN PROJECTS THAT STARTED IN 2023.

SELECT				EMPLOYEE.FIRSTNAME,AVG(EMPLOYEE.salary) as Avgsal
FROM				EMPLOYEE
INNER JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID=DEPARTMENTS.DEPARTMENTID
WHERE				YEAR(PROJECTS.STARTDATE)>=2023
GROUP BY			EMPLOYEE.FIRSTNAME


--33. LIST ALL EMPLOYEES ALONG WITH THEIR DEPARTMENT NAME, EVEN IF THEY ARE NOT ASSIGNED TO A DEPARTMENT.

SELECT				EMPLOYEE.FIRSTNAME,DEPARTMENTS.DEPARTMENTNAME
FROM				EMPLOYEE
LEFT JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID


--34. FIND ALL EMPLOYEES IN THE SAME DEPARTMENT AS THEIR MANAGER.

SELECT				EMPLOYEE.FIRSTNAME
FROM				EMPLOYEE
INNER JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
AND					DEPARTMENTS.MANAGERID=EMPLOYEE.EMPLOYEEID


--35. FIND ALL DEPARTMENTS WITH EMPLOYEES WHO HAVE NOT BEEN ASSIGNED TO ANY PROJECTS.

SELECT				EMPLOYEE.FIRSTNAME,DEPARTMENTS.DEPARTMENTNAME
FROM				EMPLOYEE
INNER JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
LEFT JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID=DEPARTMENTS.DEPARTMENTID
WHERE				PROJECTS.PROJECTID IS NULL


--36. FIND ALL EMPLOYEES WHOSE HIRE DATE IS LATER THAN THEIR PROJECTS'S START DATE.
SELECT				EMPLOYEE.FIRSTNAME,EMPLOYEE.HIREDATE,PROJECTS.STARTDATE
FROM				EMPLOYEE
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID=EMPLOYEE.DEPARTMENTID
WHERE				EMPLOYEE.HIREDATE<PROJECTS.STARTDATE


--37. FIND ALL PROJECTS THAT BELONG TO DEPARTMENTS WITHOUT EMPLOYEES.

SELECT				EMPLOYEE.EMPLOYEEID,COUNT(EMPLOYEE.EMPLOYEEID)
FROM				PROJECTS
INNER JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = PROJECTS.DEPARTMENTID
INNER JOIN			EMPLOYEE
ON					EMPLOYEE.DEPARTMENTID=DEPARTMENTS.DEPARTMENTID
GROUP BY			EMPLOYEE.EMPLOYEEID
HAVING				COUNT(EMPLOYEE.EMPLOYEEID)=0



SELECT				PROJECTS.PROJECTID,PROJECTS.PROJECTNAME
FROM				EMPLOYEE
LEFT JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
WHERE				EMPLOYEE.EMPLOYEEID IS NULL



--38. FIND DEPARTMENTS WITH MORE THAN 3 EMPLOYEES AND LIST THEIR PROJECT NAMES.
SELECT				D.DEPARTMENTID, D.DEPARTMENTNAME, P.PROJECTNAME
FROM				DEPARTMENTS D
JOIN				PROJECTS P ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE				(SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPARTMENTID = D.DEPARTMENTID) > 3;


--39. FIND EMPLOYEES WHO HAVE WORKED ON PROJECTS FOR MORE THAN 5 YEARS.
SELECT				EMPLOYEE.FIRSTNAME
FROM				EMPLOYEE
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID=EMPLOYEE.DEPARTMENTID
WHERE				DIFFERENCE(YEAR(GETDATE()),YEAR(PROJECTS.STARTDATE))>5


--40. LIST ALL PROJECTS AND THE DEPARTMENTS WHOSE MANAGERS HAVE MORE THAN 10 YEARS OF EXPERIENCE.
SELECT				P.PROJECTID, P.PROJECTNAME, D.DEPARTMENTNAME
FROM				PROJECTS P
JOIN				DEPARTMENTS D 
ON					P.DEPARTMENTID = D.DEPARTMENTID
JOIN				EMPLOYEE E 
ON					D.MANAGERID = E.EMPLOYEEID
WHERE				DATEDIFF(YEAR, E.HIREDATE, GETDATE()) > 10;


--41. FIND THE NUMBER OF EMPLOYEES IN EACH PROJECT THAT STARTED BEFORE 2023.
SELECT				PROJECTS.PROJECTNAME,COUNT(EMPLOYEE.EMPLOYEEID) AS EmployeeCount
FROM				EMPLOYEE
INNER JOIN			PROJECTS
ON					EMPLOYEE.DEPARTMENTID=PROJECTS.DEPARTMENTID
WHERE				YEAR(PROJECTS.STARTDATE)>5
GROUP BY			PROJECTS.PROJECTNAME


--42. FIND EMPLOYEES WHO WORK IN THE SAME DEPARTMENT AS A MANAGER BUT ARE NOT MANAGERS THEMSELVES.
SELECT				E.EMPLOYEEID, E.FIRSTNAME, E.LASTNAME, E.DEPARTMENTID
FROM				EMPLOYEE E
INNER JOIN				DEPARTMENTS D ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE				E.EMPLOYEEID <> D.MANAGERID;



--43. FIND ALL EMPLOYEES WHO WORK IN PROJECTS THAT STARTED IN 2023.
SELECT				DISTINCT E.EMPLOYEEID, E.FIRSTNAME, E.LASTNAME
FROM				EMPLOYEE E
JOIN				PROJECTS P 
ON					P.PROJECTID = P.PROJECTID
WHERE				YEAR(P.STARTDATE) = 2023


--44. FIND PROJECTS THAT ENDED BEFORE 2023 AND LIST THE NAMES OF THE DEPARTMENTS THEY BELONG TO.
SELECT				P.PROJECTID, P.PROJECTNAME, D.DEPARTMENTNAME
FROM				PROJECTS P
JOIN				DEPARTMENTS D ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE				YEAR(P.ENDDATE) < 2023;


--45. FIND THE TOTAL NUMBER OF EMPLOYEES WORKING IN DEPARTMENTS WHERE THE MANAGER HAS MORE THAN 10 YEARS OF EXPERIENCE.
SELECT				COUNT(e.EmployeeID) AS TotalEmployees
FROM				Employee e
JOIN				Departments d ON e.DepartmentID = d.DepartmentID
JOIN				Employee m ON d.ManagerID = m.EmployeeID
WHERE				DATEDIFF(YEAR, m.HireDate, GETDATE()) > 10;


--46. FIND DEPARTMENTS WITH EMPLOYEES WHO HAVE NOT BEEN ASSIGNED TO ANY PROJECTS.
SELECT				DISTINCT D.DEPARTMENTID, D.DEPARTMENTNAME
FROM				DEPARTMENTS D
WHERE				D.DEPARTMENTID NOT IN (SELECT DISTINCT P.DEPARTMENTID FROM PROJECTS P);


--47. FIND ALL PROJECTS HANDLED BY EMPLOYEES HIRED BEFORE 2010.
SELECT				DISTINCT P.PROJECTID, P.PROJECTNAME
FROM				PROJECTS P
JOIN				EMPLOYEE E 
ON					E.EMPLOYEEID = E.EMPLOYEEID
WHERE				YEAR(E.HIREDATE) < 2010;


--48. FIND EMPLOYEES WHO WERE HIRED AFTER THE PROJECT THEY ARE WORKING ON STARTED.
SELECT				EMPLOYEE.FIRSTNAME
FROM				EMPLOYEE
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
WHERE				EMPLOYEE.HIREDATE>PROJECTS.STARTDATE


--49. FIND ALL PROJECTS WHERE THE DEPARTMENT MANAGER'S SALARY IS LESS THAN 70,000.
SELECT				P.PROJECTID, P.PROJECTNAME
FROM				PROJECTS P
JOIN				DEPARTMENTS D 
ON					P.DEPARTMENTID = D.DEPARTMENTID
JOIN				EMPLOYEE M 
ON					D.MANAGERID = M.EMPLOYEEID
WHERE				M.SALARY < 70000;


--50. FIND DEPARTMENTS WHERE MORE THAN HALF OF THE EMPLOYEES EARN LESS THAN THE DEPARTMENT'S MANAGER.








--51. FIND THE DEPARTMENT(S) THAT HAVE THE HIGHEST AVERAGE SALARY OF EMPLOYEES.
SELECT				TOP 1 DEPARTMENTS.DEPARTMENTNAME,AVG(EMPLOYEE.SALARY)
FROM				DEPARTMENTS
INNER JOIN			EMPLOYEE
ON					EMPLOYEE.EMPLOYEEID=DEPARTMENTS.DEPARTMENTID
GROUP BY			DEPARTMENTS.DEPARTMENTNAME

SELECT DepartmentID, DepartmentName
FROM Departments
WHERE DepartmentID IN (
    SELECT DepartmentID
    FROM Employee
    GROUP BY DepartmentID
    HAVING AVG(Salary) = (SELECT MAX(avg_salary) FROM (
        SELECT AVG(Salary) AS avg_salary FROM Employee GROUP BY DepartmentID
    ) AS DeptAvg)
);


--52. FIND EMPLOYEES WHO HAVE WORKED ON MORE THAN ONE PROJECT AND LIST THE TOTAL NUMBER OF PROJECTS THEY’VE WORKED ON.
SELECT 
	e.EmployeeID, 
	e.FirstName, 
	e.LastName, 
	COUNT(p.ProjectID) AS TotalProjects
FROM Employee e
JOIN Departments d ON e.DepartmentID = d.DepartmentID
JOIN Projects p ON d.DepartmentID = p.DepartmentID
GROUP BY e.EmployeeID, e.FirstName, e.LastName
HAVING COUNT(p.ProjectID) > 1;




--53. FIND THE EMPLOYEE(S) WITH THE LONGEST TENURE IN THEIR DEPARTMENT.
SELECT 
    e.EmployeeID, 
    e.FirstName, 
    e.LastName, 
    e.HireDate, 
    d.DepartmentName, 
    DATEDIFF(YEAR, e.HireDate, GETDATE()) AS TenureYears
FROM Employee e
JOIN Departments d ON e.DepartmentID = d.DepartmentID
WHERE e.HireDate = (
    SELECT MIN(HireDate) 
    FROM Employee e2 
    WHERE e2.DepartmentID = e.DepartmentID
);



--54. FIND ALL EMPLOYEES WHO ARE PART OF DEPARTMENTS THAT HAVE COMPLETED MORE THAN 3 PROJECTS WITHIN THE LAST 5 YEARS.
SELECT				DISTINCT e.EmployeeID, e.FirstName, e.LastName, d.DepartmentName
FROM				Employee e
JOIN				Departments d ON e.DepartmentID = d.DepartmentID
JOIN				Projects p ON d.DepartmentID = p.DepartmentID
WHERE				p.EndDate BETWEEN DATEADD(YEAR, -5, GETDATE()) AND GETDATE()
GROUP BY			d.DepartmentID, e.EmployeeID, e.FirstName, e.LastName, d.DepartmentName
HAVING				COUNT(p.ProjectID) > 3;

--55. FIND EMPLOYEES WHO HAVE WORKED IN MULTIPLE DEPARTMENTS OVER TIME.











--56. LIST THE DEPARTMENTS WHERE THE TOTAL SALARY EXPENDITURE ON EMPLOYEES IS HIGHER THAN THE AVERAGE SALARY EXPENDITURE ACROSS ALL DEPARTMENTS.
WITH DeptSalary AS (
    SELECT DepartmentID, SUM(Salary) AS TotalSalary
    FROM Employee
    GROUP BY DepartmentID
),
AvgSalary AS (
    SELECT AVG(TotalSalary) AS AvgSalary
    FROM DeptSalary
)
SELECT d.DepartmentID, d.DepartmentName, ds.TotalSalary
FROM Departments d
JOIN DeptSalary ds ON d.DepartmentID = ds.DepartmentID
WHERE ds.TotalSalary > (SELECT AvgSalary FROM AvgSalary);



--57. FIND THE TOTAL SALARY OF EMPLOYEES WORKING ON PROJECTS THAT STARTED AFTER 2022 ANDENDED BEFORE 2024.
SELECT				PROJECTS.PROJECTNAME,SUM(EMPLOYEE.SALARY)
FROM				EMPLOYEE
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
WHERE				YEAR(PROJECTS.STARTDATE)>=2022 AND YEAR(PROJECTS.ENDDATE)<2024
GROUP BY			PROJECTS.PROJECTNAME





--58. FIND DEPARTMENTS WHERE THE MANAGER EARNS LESS THAN THE AVERAGE SALARY OF THE EMPLOYEES IN THAT DEPARTMENT, AND LIST THE DIFFERENCE IN SALARY.
SELECT 
    d.DepartmentID, 
    d.DepartmentName, 
    e.FirstName AS ManagerFirstName, 
    e.LastName AS ManagerLastName, 
    e.Salary AS ManagerSalary, 
    (AVG(emp.Salary) - e.Salary) AS SalaryDifference
FROM Departments d
JOIN Employee e ON d.ManagerID = e.EmployeeID
JOIN Employee emp ON d.DepartmentID = emp.DepartmentID
GROUP BY d.DepartmentID, d.DepartmentName, e.EmployeeID, e.FirstName, e.LastName, e.Salary
HAVING e.Salary < AVG(emp.Salary);


--59. LIST ALL EMPLOYEES ALONG WITH THEIR MANAGER'S NAME & PROJECT NAME.
SELECT				EMPLOYEE.FIRSTNAME,E2.FIRSTNAME AS Manager,PROJECTS.PROJECTNAME
FROM				EMPLOYEE
INNER JOIN			DEPARTMENTS
ON					DEPARTMENTS.DEPARTMENTID = EMPLOYEE.DEPARTMENTID
INNER JOIN			EMPLOYEE E2
ON					E2.EMPLOYEEID=DEPARTMENTS.MANAGERID
INNER JOIN			PROJECTS
ON					PROJECTS.DEPARTMENTID=EMPLOYEE.DEPARTMENTID


--60. FIND ALL EMPLOYEES ALONG WITH THE PROJECT NAME WITH START & END DATES AS THEY ARE WORKING ON, IF ANY.
SELECT 
	e.EmployeeID, 
	e.FirstName, 
	e.LastName, 
	d.DepartmentName, 
	p.ProjectName, 
	p.StartDate, 
	p.EndDate
FROM Employee e
LEFT JOIN Departments d ON e.DepartmentID = d.DepartmentID
LEFT JOIN Projects p ON d.DepartmentID = p.DepartmentID;
